package main

import (
	"context"
	"os"
	"server/internal/api"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/sirupsen/logrus"
)

func main() {
	dbpool := connectDB()

	server := api.NewAPIServer(os.Getenv("SERVER_PORT"), dbpool)
	server.Run()
	defer dbpool.Close()
}

// Подключение к бд (connection pool)
func connectDB() *pgxpool.Pool {
	logrus.Info("Соединение с бд")
	dbpool, err := pgxpool.New(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		logrus.Fatalf("Ошибка при подключении к бд: %v", err)
	}
	defer dbpool.Close()

	createTable(dbpool)
	return dbpool
}

// Создание таблиц в бд
func createTable(dbpool *pgxpool.Pool) {
	logrus.Info("Создание таблиц в бд")
	create := `
	    CREATE TABLE IF NOT EXISTS News(
		    Id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
			Title VARCHAR(256) NOT NULL,
		    Content VARCHAR NOT NULL,
			PRIMARY KEY (Id)
		);
		CREATE TABLE IF NOT EXISTS NewsCategories(
		    NewsId BIGINT NOT NULL,
			CategoryId BIGINT NOT NULL,
            PRIMARY KEY (NewsId, CategoryId)
		);`
	_, err := dbpool.Exec(context.Background(), create)
	if err != nil {
		logrus.Fatalf("Ошибка при создании таблиц: %v", err)
	}
}
